spring:
  application.name: spring-vault-kv
  config:
    import: vault://
  cloud:
    vault:
      uri: http://0.0.0.0:8200
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: ${VAULT_TOKEN}
logging:
  level:
    org.springframework.cloud.vault: DEBUG